djangotask/blog/urls.py
from django.contrib import admin	
from django.urls import path
from .import views


app_name = 'blog'


urlpatterns = [
    path('post/<str:slug>/edit/', views.post_edit, name='post_edit'),
    path('category/<str:slug>/edit/', views.category_edit, name='category_edit'),
    path('blog/sign_up/',views.sign_up,name="sign-up"),
	path('blog/logout/',views.logout_user, name="logout"),
    path('post/new/', views.post_new, name='post_new'),
    path('userdetail/<int:pk>/',views.userdetail, name='userdetail'),
    # path('edituser/<int:pk>/', views.edit_profile, name='edit_profile'),
    path('post/<str:slug>/', views.post_detail, name='post_detail'),
    path('category/<str:slug>/', views.category_detail, name='category_detail'),
    path('tag/<str:slug>/', views.tag_details, name='tag_details'),
    path('category/', views.category_list, name ='category_list'),
    path('tag/', views.tag_list, name ='tag_list'),
    path('login/',views.login_user, name="login"),
    path('', views.post_list, name ='post_list'),
    path('list/', views.main, name ='main'),
    # path('ulist/', views.uniquelist, name ='uniquelist'),

    
]

djangotask/djangotask/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers, serializers, viewsets
from blog import views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('api/', include('blog.apiurls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangotask/blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone
from django_extensions.db.fields import AutoSlugField
from autoslug import AutoSlugField

# Create your models here.

gender = (('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'))
slots = (("slot1", "slot1"), ("slot2", "slot2"), ("slot3", "slot3"), ("slot4", "slot4"))
status = (("Active", "Active"), ("Inactive", "Inactive"), ("Delete", "Delete"))

class User(AbstractUser):
	mobile = models.CharField(max_length=15, blank=True, null=True)
	gender = models.CharField(max_length=6, choices=gender, default='Male')
	dob = models.DateField(null=True, blank=True)
	image = models.ImageField(upload_to='user/', blank=True, null=True)
	role = models.CharField(max_length=55)

	class Meta:
		verbose_name_plural = "01. Users"

class Agency(User):
	aggency_name = models.CharField(max_length=15, blank=True, null=True)

	class Meta:
		verbose_name_plural = "01. Agency"

class Category(models.Model):
	title= models.CharField(max_length=200)
	text=models.TextField()
	slug = AutoSlugField(populate_from='title', max_length=160, editable=True)
	parent=models.ForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
	created_date = models.DateTimeField(default = timezone.now)

	class Meta:
		verbose_name_plural = "categories" 

	def __str__(self):
		return self.title

	def slugify_function(self, content):
		return content.replace('_', '-').lower()

class Tag(models.Model):
	title = models.CharField(blank=True, max_length=200)
	text=models.TextField(default=True)
	slug = AutoSlugField(populate_from='title', max_length=160, editable=True)
	created_date = models.DateTimeField(default = timezone.now)

	def __str__(self):
		return self.title

	def slugify_function(self, content):
		return content.replace('_', '-').lower()

class Post(models.Model):
	tag = models.ManyToManyField('Tag')
	category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.CASCADE, related_query_name="posts")
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	title = models.CharField(max_length=200)
	text = models.TextField()
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)
	slug = AutoSlugField(populate_from='title', max_length=160, editable=True)
	

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.title 

	def slugify_function(self, content):
		return content.replace('_', '-').lower()

class Appoitment(models.Model):
	name = models.CharField(max_length=100)
	text = models.TextField()
	date = models.DateField()
	slot1 = models.TimeField(default='09:00:00')
	slot2 = models.TimeField(default='11:00:00')
	slot3 = models.TimeField(default='14:00:00')
	slot4 = models.TimeField(default='16:00:00')
	slot = models.CharField(max_length=20, choices=slots, default='slot1')

	def __str__(self):
		return str(self.name)

class Uservisited(models.Model):
	user = models.ForeignKey('User', on_delete=models.CASCADE)
	url = models.URLField(max_length = 200)

	def __str__(self):
		return str(self.user.username)

class Company(models.Model):
	user = models.ForeignKey('User', on_delete=models.CASCADE)
	name = models.CharField(max_length=100, verbose_name="company name")
	address = models.CharField(max_length=100, verbose_name="company address")
	position = models.CharField(max_length=100, verbose_name="employee position")

	def __str__(self):
		return str(self.name)

djangotask/blog/forms.py
from django import forms
from .models import *
# from django.contrib.auth.models import User
# from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'text',)


class categoryForm(forms.ModelForm):

	class Meta:
		model = Category
		fields=('title' , 'text',)

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('user', 'name', 'address', 'position',)

    def __init__(self, user, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)
        self.fields['user'].queryset = User.objects.filter(user=user)

djangotask/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import *
from .forms import PostForm,categoryForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
import random
import numpy as np
from .api import PostFilter
from .decorators import save_user
User = get_user_model()

# Create your views here.

@save_user
def category_list(request):
	categories=Category.objects.all()
	return render(request, 'blog/category_list.html', {'categories':categories})

@save_user
def category_detail(request,slug):
	category = get_object_or_404(Category, slug=slug)
	posts= Post.objects.filter(category=category)
	tableFilter = PostFilter(request.GET, queryset=posts)
	# posts = myFilter.qs
	return render(request, 'blog/category_detail.html', {'posts': posts, 'category':category,'tableFilter': tableFilter})

@save_user
def category_edit(request, slug):
	category = get_object_or_404(Category, slug=slug)
	if request.method == "POST":
		form = CategoryForm(request.POST, instance=category)
		if form.is_valid():
			category = form.save(commit=False)
			category.created_date = timezone.now()
			category.save()
			return redirect('blog:category_detail', slug=category.slug)
	else:
		form = CategoryForm(instance=category)
	return render(request, 'blog/category_edit.html', {'form': form})

@save_user
def post_list(request):
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
	return render(request, 'blog/post_list.html', {'posts': posts})

@save_user
def post_detail(request, slug):
	post = get_object_or_404(Post, slug=slug)
	# comments=Comment.objects.filter(post=post, parent=None)
	# new_comment=None
	# if request.method == "POST":
	# 	form = CommentForm(request.POST)
	# 	if form.is_valid():	
	# 		text= request.POST.get('text')
	# 		name= request.POST.get('name')
	# 		reply_id=request.POST.get('comment_id')
	# 		comment_obj=None
	# 		if reply_id:
	# 			comment_obj=Comment.objects.get(id=reply_id)
			
	# 		new_comment = Comment.objects.create(post=post, parent=comment_obj, text=text, name=name)
	# 		new_comment.save()
	# 		return redirect('blog:post_detail', slug=post.slug)

	# else:
	# 	form = CommentForm()
	return render(request, 'blog/post_details.html', {'post': post})

@save_user
def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_list')
		
	else:
		form = PostForm()
	return render(request, 'blog/post_edit.html', {'form': form})

@save_user
def post_edit(request, slug):
	post = get_object_or_404(Post, slug=slug)
	if request.method == "POST":
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', slug=post.slug)
	else:
		form = PostForm(instance=post)
	return render(request, 'blog/post_edit.html', {'form': form})

@save_user
def tag_list(request):
	tags= Tag.objects.all()
	print(tags)
	return render(request, 'blog/tag_list.html', {'tags':tags})

@save_user
def tag_details(request, slug):
	tag = get_object_or_404(Tag, slug=slug)
	print(tag)
	posts=Post.objects.filter(tag__slug=tag)
	return render(request, 'blog/tag_details.html', {'tag':tag, 'posts': posts})

def sign_up(request):  
	context = {}
	form = UserCreationForm(request.POST or None)
	if request.method == "POST":
		if form.is_valid():
			user = form.save()
			auth.login(request, user)
			return render(request,'blog/post_list.html')
	context['form']=form
	return render(request,'blog/sign_up.html',context)

def login_user(request):

	if request.method == "POST":
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request,user)
			return render(request, 'blog/post_list.html')
	else:
		return render(request, 'blog/login.html')

def logout_user(request):
	logout(request)
	return render(request, 'blog/post_list.html')

@login_required
def userdetail(request, pk):
	user = User.objects.get(pk=pk)
	print(user.image,'1111111111')
	# userimg=  Userprofile.objects.filter(user= request.user).first()
	return render(request, 'blog/userdetail.html',{'user':user})


def randomlist():
	random_list = np.random.randint(60, size=(87))
	return random_list

def uniquelist(random_list):
	unique_list = list(set(random_list))
	return unique_list

@save_user
def main(request):
    random_list = randomlist()
    unique_list = uniquelist(random_list)
    K=15
    new_unique_list = list(map(lambda x : x + K, unique_list))
    odd_list = list(filter(lambda x: (x%2 != 0) , new_unique_list))
    even_list = list(filter(lambda x: (x%2 == 0) , new_unique_list))
    odd_list_sum = sum(odd_list)
    even_list_sum = sum(even_list)
    return render(request, 'blog/randomlist.html',{'random_list':random_list,'unique_list':unique_list,'new_unique_list':new_unique_list,'odd_list':odd_list,'even_list':even_list,'odd_list_sum':odd_list_sum,'even_list_sum':even_list_sum})

djangotask/blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
<!-- Comments Form --> 
<h2>Add a new comment</h2>
<form method="POST" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add comment</button>
</form>

<!-- Comment with nested comments -->
{% for comment in comments %}
    <div class="comment" style="background-color: powderblue">
        <p class="info">{{ comment.name }} | {{ comment.created }}</p>
            {{ comment.text|linebreaks }}

            	<h5>Replay</h5>
					<form method="POST" class="post-form">{% csrf_token %}
						{{ form.as_p }}
						<!-- Hidden input for parent comment.id -->
						<input type="hidden" name="parent_id" value="{{ comment.id }}">
						<input class="btn btn-primary" type="submit" value="Replay">
					</form>

					{% for replay in comment.replies.all %}
						<div class="replay" style="background-color: powderblue">
						<p class="info">{{ replay.name }} | {{ replay.created }}</p>
						<li>{{ replay.text }}</li>
						</div>
					{% endfor %}
    </div>
{% empty %}
<h4>There are no comments yet.</h4>
{% endfor %}
{% endblock %}

djangotask/blog/templates/blog/base.html
{% load static %}
<html>
	<head>
		<title>Django app</title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	</head>
	<body>
		<div class="page-header">
			{% if user.is_authenticated %}
			<!-- {% csrf_token %} -->
			<a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
			<a href="{% url 'blog:logout' %}" class="top-menu menu-nav-custom">logout</a>
			<a style="color: blue;" href="{% url 'blog:userdetail' pk=user.pk %}" class="top-menu menu-nav-custom">Hi {{user}}</a>
				
			
			{% else %}
			<a href="{% url 'blog:sign-up' %}" class="top-menu menu-nav-custom">sign_up</a>
			<a href="{% url 'blog:login' %}" class="top-menu menu-nav-custom">login</a>
				
			{% endif %}
			<h1>
				<a href="/">Django girls blog</a>
			</h1>
		</div>
		<div class="content container">
			<div class="row">
				<div class="col-md-8">
					{% block content %}
					{% endblock %}
				</div>
			</div>
		</div>
	</body>
</html>

djangotask/blog/templates/blog/category_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="category">
        <h2>{{ category.title }}</h2>
        <p>{{ category.text|linebreaksbr }}</p>
        {% for post in posts%}
        <div class="post">
        	<h2><a href="{% url 'blog:post_detail' slug=post.slug %}">{{ post.title }}</a></h2>
        	<p>{{ post.text }}</p>
        </div>
        {% endfor %}
    </div>
    <div class="row">
	    <div class="col">
			<div class="card card-body">
				<form method="get">
			        {{tableFilter.form}}
			        <button class="btn btn-primary" type="submit">Search</button>
				</form>
			</div>
	    </div>
	</div>
{% endblock %}

djangotask/blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for category in categories %}
        <div class="category">
            <h2><a href="{% url 'blog:category_detail' slug=category.slug %}">{{ category.title }}</a></h2>
            <p>{{ category.text|linebreaksbr }}</p>

        </div>
    {% endfor %}
{% endblock %}   		

djangotask/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
	<div id="content-container" class="container p-none">
		<div class="lgn-container col-lg-8">
			<form id="login-form" method="post"> 
				{% csrf_token %}
				<table class="table">
					<tr>
						<td><label for="id_username">Username</label></td>
						<td><input id="id_username" name="username" 
								   type="text" class="form-control"></td>
					</tr>
					<tr>
						<td><label for="id_password">Password</label></td>
						<td><input id="id_password" name="password" 
								   type="password" class="form-control"></td>
					</tr>
				</table>
				{% if form.errors %}
					<p class=" label label-danger">
						Your username and password didn't match. 
						Please try again.
					</p>
				{% endif %}

				<input type="submit" value="Login" 
					   class="btn btn-primary pull-right" />
				<input type="hidden" name="next" value="{{ next }}" />
			</form>
		</div>
	</div>
{% endblock content %}

djangotask/blog/templates/blog/post_details.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'blog:post_edit' slug=post.slug %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
   
   

   <!--  <div class="container">
        <div class="row">
            {% for comment in comments %}
                <div class="comment">
                    <strong>{{ comment.name }}</strong>
                    <p>{{ comment.text|linebreaks }}</p> 
                </div> 
                {% for reply in comment.replies.all %}
                    <div class="reply">
                        <strong>{{ reply.name }}</strong>
                        <p>{{ reply.text|linebreaks}}</p>
                    </div>
                {% endfor %}

                <h3> Reply</h3>
                <form method="POST" id="commentform">{% csrf_token %}>
                    {{ form.as_p }}
                    <input type="hidden" name="comment_id" value="{{comment.id}}">
                    <input type="submit" value="submit reply">   
                </form>
                {% empty %}
                    <p>No comments here yet :(</p>
            {% endfor %}         
        </div>             
    </div>
     <h3> Leave a comment</h3>
    <form method="POST" id="commentform">{% csrf_token %}>
        {{ form.as_p }}
        <input type="submit" value="submit Comment">
    </form> -->

{% endblock %}

djangotask/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>Edit post</h2>
    <form method="POST" class="post-form">
    	{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

djangotask/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
	{% for post in posts %}
		<div class="post">
			<div class="date">
				{{ post.published_date }}
			</div>
			<h2>
				<a href="{% url 'blog:post_detail' slug=post.slug %}">{{ post.title }}</a>
			</h2>
			<p>{{ post.text|linebreaksbr }}</p>
		</div>
	{% endfor %}
{% endblock %}  

djangotask/blog/templates/blog/randomlist.html
{% extends 'blog/base.html' %}

{% block content %}

<h2>random list:{{random_list}}</h2>

<h2>unique list:{{unique_list}}</h2>

<h2>unique list after adding 15 to each item:{{new_unique_list}}</h2>

<h2>odd list:{{odd_list}}</h2>

<h2>even list:{{even_list}}</h2>

<h2>sum of odd list:{{odd_list_sum}}</h2>

<h2>sum of even list:{{even_list_sum}}</h2>

{% endblock %}

djangotask/blog/templates/blog/sign_up.html
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Sign up">
</form>

djangotask/blog/templates/blog/tag_details.html
{% extends 'blog/base.html' %}

{% block content %}
	<div class="Tag">
		<h2>{{ tag.title }}</h2>
		 <p>{{ tag.text|linebreaksbr }}</p>
		 <p>{{ tag.slug|linebreaksbr }}</p>
		 {% for post in posts %}
		<div class="post">
			<h2><a href="{% url 'blog:post_detail' slug=post.slug %}">{{ post.title }}</a></h2>
		</div>
		{% endfor %}
	</div>
{% endblock %}

djangotask/blog/templates/blog/tag_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for tag in tags %}
        <div class="tag">
            <h2><a href="{% url 'blog:tag_details' slug=tag.slug %}">{{ tag.title }}</a></h2>
            <p>{{ tag.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}   	

djangotask/blog/templates/blog/userdetail.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>{{ user.userprofile.user }} welcome to your profile page</h1>        
    <h2>first_name: {{ user.first_name }}</h2>
    <h2>last_name: {{ user.last_name }}</h2>

    <img src="{% if user.image %}{{ user.image.url }}{%endif%}" width = "150" height = "150"  />
{% endblock %}

djangotask/blog/templates/blog/useredit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>Edit user profile</h2>
    <form method="POST" class="Profile-form" enctype="multipart/form-data">
    	{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">update</button>
    </form>
{% endblock %}